// This file is generated by npm run build:icons
  
  export type IconName =
	| "arrow-down-square"
	| "arrow-left-square"
	| "arrow-right"
	| "arrow-top-right"
	| "arrow-up-square"
	| "bullet"
	| "camera"
	| "card-stack"
	| "check"
	| "checkmark"
	| "chevron-down"
	| "chevron-left"
	| "chevron-right"
	| "chevron-up"
	| "close-small"
	| "close"
	| "collapse"
	| "expand"
	| "loader-circle"
	| "loader-pinwheel"
	| "pause"
	| "play"
	| "star";
  