// This file is generated by npm run build:icons
  
  export type IconName =
	| "lg-chevron-down"
	| "lg-chevron-left"
	| "lg-chevron-right"
	| "lg-chevron-up"
	| "lg-collapse"
	| "lg-expand"
	| "sm-arrow-right"
	| "sm-arrow-top-right"
	| "sm-bullet"
	| "sm-checkmark"
	| "sm-close-thin"
	| "sm-pause"
	| "sm-play"
	| "sm-star";
  