// This file is generated by npm run build:icons

export type IconName =
  | "arrow-down-square"
  | "arrow-left-square"
  | "arrow-up-square"
  | "camera"
  | "card-stack"
  | "check"
  | "loader-circle"
  | "loader-pinwheel";
