import { defineType } from "sanity";
import { imageField } from "../generator-fields/image.field";
import { linksField } from "../generator-fields/links.field";

// This is where we put stuff that should be generated by the typegen but not used anywhere else
export const typegenSettingsSchema = defineType({
  type: "document",
  name: "typegenSettings",
  title: "Typegen",
  fields: [
    linksField({
      name: "fullLinks",
      title: "Full links",
      includeExternal: true,
      includeLinkGroup: true,
      includeDescriptionInLinkGroup: true,
      includeDownload: true,
      includeInternal: true,
      includeCustomTitle: true,
    }),
    imageField({
      name: "image",
      title: "Image",
    }),
  ],
});
